name: addition
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - more-itertools
  - tqdm
  - scipy
  - pytorch
  - torchvision
  - mpi4py
  - pyyaml
  - pip
  - pip:
      - python-markdown-math
